package jpl2;

public class Book 
{

    String newLine = System.getProperty("line.separator");
    String[] pages = 
    {
                    "______________________________________________________________________________"
        + newLine + "|                             Big Book of                                    |"    
        + newLine + "|                             Lorem Ipsum                                    |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod    |" 
        + newLine + "| tempor incididunt ut labore et dolore magna aliqua. Mi ipsum faucibus      |" 
        + newLine + "| vitae aliquet nec ullamcorper sit amet. Magna fermentum iaculis eu non     |" 
        + newLine + "| diam phasellus. Cras tincidunt lobortis feugiat vivamus. Velit scelerisque |"
        + newLine + "| in dictum non consectetur a erat nam. Urna cursus eget nunc scelerisque    |" 
        + newLine + "| viverra mauris in aliquam sem. Nec tincidunt praesent semper feugiat       |"
        + newLine + "| nibh sed pulvinar proin. Faucibus et molestie ac feugiat sed lectus        |"
        + newLine + "| vestibulum. Malesuada fames ac turpis egestas sed tempus urna et           |"
        + newLine + "| pharetra. Nam aliquam sem et tortor consequat id porta nibh venenatis.     |"
        + newLine + "| Amet cursus sit amet dictum. Commodo nulla facilisi nullam vehicula        |"
        + newLine + "| ipsum a arcu cursus. Proin libero nunc consequat interdum varius sit       |"
        + newLine + "| amet mattis vulputate. Malesuada proin libero nunc consequat interdum.     |"
        + newLine + "| Ornare quam viverra orci sagittis. Velit ut tortor pretium viverra         |"
        + newLine + "| suspendisse potenti nullam ac tortor. Nunc non blandit massa enim nec.     |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  1                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Hac habitasse platea dictumst quisque sagittis purus. Non odio euismod     |" 
        + newLine + "| lacinia at quis risus sed vulputate. Mi quis hendrerit dolor magna eget. Mi|" 
        + newLine + "| sit amet mauris commodo quis imperdiet massa tincidunt. Donec et odio      |" 
        + newLine + "| pellentesque diam volutpat commodo. Quam nulla porttitor massa id.         |"
        + newLine + "| Cursus vitae congue mauris rhoncus aenean vel elit. Convallis posuere      |" 
        + newLine + "| morbi leo urna molestie. Sem et tortor consequat id porta nibh venenatis   |"
        + newLine + "| cras sed. Commodo odio aenean sed adipiscing diam donec adipiscing         |"
        + newLine + "| tristique. Nullam non nisi est sit amet facilisis magna etiam tempor.      |"
        + newLine + "| Viverra vitae congue eu consequat ac felis donec et. Egestas sed sed risus |"
        + newLine + "| pretium quam vulputate dignissim suspendisse in.                           |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  2                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Sed cras ornare arcu dui vivamus arcu felis bibendum. Tincidunt ornare     |" 
        + newLine + "| massa eget egestas purus. Diam in arcu cursus euismod quis. Est ante in    |" 
        + newLine + "| nibh mauris cursus mattis. Ultrices neque ornare aenean euismod            |" 
        + newLine + "| elementum nisi quis eleifend. Quam elementum pulvinar etiam non quam       |"
        + newLine + "| lacus. Diam donec adipiscing tristique risus nec feugiat. In tellus integer|" 
        + newLine + "| feugiat scelerisque varius morbi enim nunc faucibus. Urna condimentum      |"
        + newLine + "| mattis pellentesque id nibh. Quis hendrerit dolor magna eget est lorem.    |"
        + newLine + "| Sit amet massa vitae tortor. Odio eu feugiat pretium nibh ipsum            |"
        + newLine + "| consequat nisl vel. Viverra aliquet eget sit amet. Vitae tortor            |"
        + newLine + "| condimentum lacinia quis vel eros donec ac odio. Nunc sed id semper        |"
        + newLine + "| risus in hendrerit. Viverra nibh cras pulvinar mattis nunc sed blandit.    |"
        + newLine + "| Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi           |"
        + newLine + "| tincidunt ornare. Sapien nec sagittis aliquam malesuada.                   |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  3                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Id velit ut tortor pretium viverra suspendisse potenti nullam. Risus       |" 
        + newLine + "| ultricies tristique nulla aliquet enim tortor. Id aliquet lectus proin nibh|" 
        + newLine + "| nisl condimentum id venenatis a. Quis blandit turpis cursus in hac         |" 
        + newLine + "| habitasse. Amet luctus venenatis lectus magna fringilla urna porttitor     |"
        + newLine + "| rhoncus. Faucibus et molestie ac feugiat. Odio ut sem nulla pharetra diam  |" 
        + newLine + "| sit. Diam phasellus vestibulum lorem sed. Pulvinar neque laoreet           |"
        + newLine + "| suspendisse interdum consectetur libero. Amet nisl purus in mollis. A      |"
        + newLine + "| arcu cursus vitae congue mauris. Sed blandit libero volutpat sed cras      |"
        + newLine + "| ornare arcu. Sit amet est placerat in egestas erat imperdiet. Blandit      |"
        + newLine + "| aliquam etiam erat velit scelerisque. Posuere ac ut consequat semper.      |"
        + newLine + "| Donec et odio pellentesque diam volutpat commodo sed. Turpis egestas       |"
        + newLine + "| integer eget aliquet nibh praesent tristique magna sit. Rutrum tellus      |"
        + newLine + "| pellentesque eu tincidunt.                                                 |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  4                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Orci porta non pulvinar neque. Sit amet est placerat in egestas. Eu        |" 
        + newLine + "| volutpat odio facilisis mauris sit amet massa vitae. Elementum nisi quis   |" 
        + newLine + "| eleifend quam adipiscing vitae proin sagittis. Sed adipiscing diam donec   |" 
        + newLine + "| adipiscing tristique risus nec. Tempus egestas sed sed risus pretium quam  |"
        + newLine + "| vulputate. Mi eget mauris pharetra et ultrices neque. Ante in nibh mauris  |" 
        + newLine + "| cursus mattis molestie a iaculis. Scelerisque mauris pellentesque pulvinar |"
        + newLine + "| pellentesque habitant. A diam sollicitudin tempor id. Aliquet enim tortor  |"
        + newLine + "| at auctor. Magna fringilla urna porttitor rhoncus dolor. Magna sit amet    |"
        + newLine + "| purus gravida quis blandit turpis cursus. Magna sit amet purus gravida     |"
        + newLine + "| quis blandit. Neque volutpat ac tincidunt vitae semper quis. Euismod       |"
        + newLine + "| elementum nisi quis eleifend quam. Pulvinar pellentesque habitant morbi    |"
        + newLine + "| tristique senectus.                                                        |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  5                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Sed adipiscing diam donec adipiscing tristique risus nec. Lacus            |" 
        + newLine + "| vestibulum sed arcu non odio euismod lacinia at quis. Parturient montes    |" 
        + newLine + "| nascetur ridiculus mus mauris vitae ultricies. In eu mi bibendum neque     |" 
        + newLine + "| egestas congue quisque egestas. Amet mattis vulputate enim nulla aliquet.  |"
        + newLine + "| At tellus at urna condimentum mattis pellentesque. Et malesuada fames      |" 
        + newLine + "| ac turpis egestas sed tempus urna. Pretium fusce id velit ut tortor pretium|"
        + newLine + "| viverra. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Est|"
        + newLine + "| ante in nibh mauris cursus mattis molestie a iaculis. Lobortis elementum   |"
        + newLine + "| nibh tellus molestie. Non consectetur a erat nam at lectus urna duis       |"
        + newLine + "| convallis. Ultrices sagittis orci a scelerisque purus. Vel elit scelerisque|"
        + newLine + "| mauris pellentesque pulvinar pellentesque. Lectus arcu bibendum at         |"
        + newLine + "| varius vel pharetra. Id interdum velit laoreet id donec ultrices tincidunt.|"
        + newLine + "| Aliquam sem et tortor consequat id. Egestas quis ipsum suspendisse         |"
        + newLine + "| ultrices gravida dictum fusce ut. Vitae elementum curabitur vitae nunc     |"
        + newLine + "| sed velit dignissim sodales ut. At tellus at urna condimentum mattis       |"    
        + newLine + "| pellentesque id.                                                           |"    
        + newLine + "|                                  6                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Elementum pulvinar etiam non quam lacus suspendisse faucibus               |" 
        + newLine + "| interdum posuere. Eu scelerisque felis imperdiet proin. Non pulvinar       |" 
        + newLine + "| neque laoreet suspendisse interdum. Nunc mattis enim ut tellus             |" 
        + newLine + "| elementum sagittis. Id porta nibh venenatis cras sed. Cursus metus         |"
        + newLine + "| aliquam eleifend mi in nulla. Facilisis mauris sit amet massa vitae tortor |" 
        + newLine + "| condimentum lacinia quis. Tincidunt ornare massa eget egestas purus.       |"
        + newLine + "| Vitae tempus quam pellentesque nec nam aliquam. Ipsum consequat nisl       |"
        + newLine + "| vel pretium. Eu scelerisque felis imperdiet proin. Lacus suspendisse       |"
        + newLine + "| faucibus interdum posuere lorem ipsum. Ultricies tristique nulla aliquet   |"
        + newLine + "| enim tortor. Laoreet suspendisse interdum consectetur libero id. Semper    |"
        + newLine + "| eget duis at tellus at urna. Integer vitae justo eget magna.               |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  7                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Proin libero nunc consequat interdum. Aliquam malesuada bibendum           |" 
        + newLine + "| arcu vitae elementum. Posuere urna nec tincidunt praesent. Justo eget      |" 
        + newLine + "| magna fermentum iaculis eu. Diam in arcu cursus euismod quis viverra.      |" 
        + newLine + "| Ut tellus elementum sagittis vitae et leo duis ut. Ante in nibh mauris     |"
        + newLine + "| cursus mattis. Aliquet eget sit amet tellus cras adipiscing enim. Et       |" 
        + newLine + "| malesuada fames ac turpis egestas. Bibendum at varius vel pharetra vel.    |"
        + newLine + "| Leo in vitae turpis massa. Mattis molestie a iaculis at. Tortor at risus   |"
        + newLine + "| viverra adipiscing at in tellus integer feugiat sit amet volutpat consequat|"
        + newLine + "| mauris. Ut enim blandit volutpat maecenas. Pellentesque habitant morbi     |"
        + newLine + "| tristique senectus et. Purus ut faucibus pulvinar elementum integer enim.  |"
        + newLine + "| Aliquam vestibulum morbi blandit cursus. Sollicitudin tempor id eu nisl.   |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  8                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Dignissim suspendisse in est ante in nibh mauris cursus. Sit amet massa    |" 
        + newLine + "| vitae tortor condimentum lacinia quis vel eros. Lacinia quis vel eros      |" 
        + newLine + "| donec ac odio tempor orci. Enim tortor at auctor urna. Tempus urna et      |" 
        + newLine + "| pharetra pharetra massa massa ultricies. Convallis posuere morbi leo       |"
        + newLine + "| urna molestie at elementum eu. Malesuada nunc vel risus commodo            |" 
        + newLine + "| viverra maecenas accumsan. In hendrerit gravida rutrum quisque non         |"
        + newLine + "| tellus orci. Purus non enim praesent elementum facilisis leo vel fringilla |"
        + newLine + "| est. Erat velit scelerisque in dictum non consectetur a. Interdum posuere  |"
        + newLine + "| lorem ipsum dolor sit amet consectetur. Ut diam quam nulla porttitor.      |"
        + newLine + "| Praesent tristique magna sit amet purus gravida quis blandit turpis.       |"
        + newLine + "| Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin.      |"
        + newLine + "| Nunc vel risus commodo viverra maecenas. Fermentum odio eu feugiat         |"
        + newLine + "| pretium nibh ipsum. Quis varius quam quisque id diam vel.                  |"
        + newLine + "|                                                                            |"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                  9                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",

                    "______________________________________________________________________________"
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "|                                                                            |"    
        + newLine + "| Porttitor eget dolor morbi non arcu risus quis varius. Suspendisse         |" 
        + newLine + "| interdum consectetur libero id faucibus. Nunc sed augue lacus viverra      |" 
        + newLine + "| vitae congue eu. Vel elit scelerisque mauris pellentesque pulvinar         |" 
        + newLine + "| pellentesque habitant morbi tristique. Ipsum consequat nisl vel pretium    |"
        + newLine + "| lectus quam. Aliquam id diam maecenas ultricies mi eget mauris. Turpis     |" 
        + newLine + "| massa tincidunt dui ut ornare lectus sit amet. Rhoncus est pellentesque    |"
        + newLine + "| elit ullamcorper dignissim cras tincidunt. Nunc faucibus a pellentesque    |"
        + newLine + "| sit amet porttitor eget dolor. Rhoncus urna neque viverra justo nec        |"
        + newLine + "| ultrices. Interdum velit euismod in pellentesque massa placerat duis.      |"
        + newLine + "| Aliquam ut porttitor leo a diam. Sed velit dignissim sodales ut eu         |"
        + newLine + "| sem. Varius quam quisque id diam vel quam elementum pulvinar.              |"
        + newLine + "| Commodo nulla facilisi nullam vehicula ipsum. Suscipit adipiscing          |"
        + newLine + "| bibendum est ultricies integer quis auctor elit sed. Sed arcu non odio     |"
        + newLine + "| euismod lacinia at quis risus. Enim nunc faucibus a pellentesque. Ultrices |"
        + newLine + "| eros in cursus turpis massa. Consectetur adipiscing elit duis tristique    |"    
        + newLine + "| sollicitudin nibh sit amet.                                                |"    
        + newLine + "|                                 10                                         |"    
        + newLine + "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾"

    };
    boolean nextPage = false;
    boolean lastPage = false;
    String output = "";

    int numPages = 9;

    String pageChange(int pageTo)
    {
        if(pageTo <= numPages && pageTo >= 0)
        {
            output = pages[pageTo];
            return  output;
        }
        return "Unable to perform action";
    }

}


